"""Delete Itempur

Revision ID: 1cccc4d4412f
Revises: fd13cbb22b4b
Create Date: 2024-12-15 00:13:14.125441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cccc4d4412f'
down_revision: Union[str, None] = 'fd13cbb22b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_item')
    op.add_column('party', sa.Column('purchase_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'party', 'purchases', ['purchase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'party', type_='foreignkey')
    op.drop_column('party', 'purchase_id')
    op.create_table('purchase_item',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='purchase_item_product_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name='purchase_item_purchase_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_item_pkey')
    )
    # ### end Alembic commands ###
