"""update party column quantity

Revision ID: c2fb2c4eed16
Revises: 2e61df661d85
Create Date: 2024-11-28 16:35:09.889772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2fb2c4eed16"
down_revision: Union[str, None] = "2e61df661d85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "party", sa.Column("quantity", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("party", "quantity")
    # ### end Alembic commands ###
